/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.company.resume.panel;

import com.company.dao.inter.UserSkillDaoInter;
import com.company.entity.Skill;
import com.company.entity.User;
import com.company.entity.UserSkill;
import com.company.main.Context;
import com.company.resume.config.Config;
import com.company.resume.entityUI.SkillUI;
import com.company.resume.frame.SkillAdd;
import com.company.resume.frame.SkillUpdate;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author PC
 */
public class SkillsPanel extends javax.swing.JPanel {

    UserSkillDaoInter userSkillDao = Context.instanceUserSkillDao();

    /**
     * Creates new form SkillsPanel
     */
    public SkillsPanel() {
        initComponents();
    }

    private List<UserSkill> userSkills;

    private void fillTable() {
        User user = Config.loggedInUser;
        userSkills = userSkillDao.getAllSkillByUserId(user.getId());

        Vector<Vector> raws = new Vector<>();
        userSkills.forEach(skill -> {
            Vector raw = new Vector();
            raw.add(skill.getSkill().getName());
            raw.add(skill.getPower());
            raws.add(raw);
        });
        Vector<String> columns = new Vector<>();
        columns.add("Skill");
        columns.add("Power");

        DefaultTableModel model = new DefaultTableModel();
        tblSkills.setModel(model);
        model.setDataVector(raws, columns);
    }

    public void fillComponents() {
        fillTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frameSkillAdd = new javax.swing.JFrame();
        frameSkillUpdate = new javax.swing.JFrame();
        pnlSkill = new javax.swing.JPanel();
        lblSkill = new javax.swing.JLabel();
        cbSkill = new javax.swing.JComboBox<>();
        sliderSkillPower = new javax.swing.JSlider();
        txtSkill = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lblPower = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSkills = new JTable((TableModel) tblSkills){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        pnlControl = new javax.swing.JPanel();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();

        frameSkillAdd.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        frameSkillAdd.setResizable(false);

        javax.swing.GroupLayout frameSkillAddLayout = new javax.swing.GroupLayout(frameSkillAdd.getContentPane());
        frameSkillAdd.getContentPane().setLayout(frameSkillAddLayout);
        frameSkillAddLayout.setHorizontalGroup(
            frameSkillAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        frameSkillAddLayout.setVerticalGroup(
            frameSkillAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        frameSkillUpdate.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        frameSkillUpdate.setResizable(false);

        lblSkill.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSkill.setText("Skill :");

        cbSkill.setToolTipText("");

        sliderSkillPower.setMaximum(10);
        sliderSkillPower.setMinimum(1);
        sliderSkillPower.setToolTipText("1");
        sliderSkillPower.setValue(1);
        sliderSkillPower.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderSkillPowerStateChanged(evt);
            }
        });

        txtSkill.setToolTipText("Skill");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblPower.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPower.setText("Power :");

        javax.swing.GroupLayout pnlSkillLayout = new javax.swing.GroupLayout(pnlSkill);
        pnlSkill.setLayout(pnlSkillLayout);
        pnlSkillLayout.setHorizontalGroup(
            pnlSkillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSkillLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSkillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPower)
                    .addComponent(lblSkill, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSkillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlSkillLayout.createSequentialGroup()
                        .addComponent(cbSkill, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(txtSkill, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sliderSkillPower, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSkillLayout.setVerticalGroup(
            pnlSkillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSkillLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSkillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSkill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSkill, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSkill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlSkillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sliderSkillPower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave)
                    .addComponent(lblPower))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout frameSkillUpdateLayout = new javax.swing.GroupLayout(frameSkillUpdate.getContentPane());
        frameSkillUpdate.getContentPane().setLayout(frameSkillUpdateLayout);
        frameSkillUpdateLayout.setHorizontalGroup(
            frameSkillUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSkill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        frameSkillUpdateLayout.setVerticalGroup(
            frameSkillUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSkill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(tblSkills);

        btnDelete.setBackground(new java.awt.Color(211, 50, 58));
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(51, 153, 0));
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlControlLayout = new javax.swing.GroupLayout(pnlControl);
        pnlControl.setLayout(pnlControlLayout);
        pnlControlLayout.setHorizontalGroup(
            pnlControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlControlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEdit)
                .addGap(12, 12, 12)
                .addComponent(btnDelete)
                .addContainerGap())
        );
        pnlControlLayout.setVerticalGroup(
            pnlControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlControlLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(pnlControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnEdit)
                    .addComponent(btnAdd))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
            .addComponent(pnlControl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        frameSkillAdd = new SkillAdd();
        frameSkillAdd.setVisible(true);
        
        reloadTable((SkillAdd) frameSkillAdd);
    }//GEN-LAST:event_btnAddActionPerformed

    private void reloadTable(JFrame frame) {
        Timer timer = new Timer(1000, null);
        timer.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                fillTable();

                if (!frame.isShowing()) {
                    timer.stop();
                }
            }
        });
        timer.start();
    }

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int[] selectedRows = tblSkills.getSelectedRows();

        if (selectedRows.length == 0) {
            return;
        }

        int confirmAnswer = showDeleteConfirmDialog();

        if (confirmAnswer == 0) {
            deleteSelectedItems(selectedRows);
            fillTable();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        if (tblSkills.getSelectedRow() < 0) {
            return;
        }
        
        frameSkillUpdate = new SkillUpdate(userSkills.get(tblSkills.getSelectedRow()));
        frameSkillUpdate.setVisible(true);
        reloadTable(frameSkillUpdate);

    }//GEN-LAST:event_btnEditActionPerformed

    private void sliderSkillPowerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderSkillPowerStateChanged
        // TODO add your handling code here:
        sliderSkillPower.setToolTipText(new Integer(sliderSkillPower.getValue()).toString());
    }//GEN-LAST:event_sliderSkillPowerStateChanged

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private int[] getSelectedItemsUserSkillId(int[] selectedRows) {
        int[] selectedUserSkillsId = new int[selectedRows.length];

        for (int i = 0; i < selectedRows.length; i++) {
            selectedUserSkillsId[i] = userSkills.get(selectedRows[i]).getId();
        }

        return selectedUserSkillsId;
    }

    private boolean deleteSelectedItems(int[] selectedRows) {
        return userSkillDao.removeSelectedItems(getSelectedItemsUserSkillId(selectedRows));
    }

    private int showDeleteConfirmDialog() {
        return JOptionPane.showOptionDialog(null,
                "Are you sure you want to delete ?",
                "Confirm Window",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                new String[]{"Yes, please",
                    "Cancel"},
                "");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<Skill> cbSkill;
    private javax.swing.JFrame frameSkillAdd;
    private javax.swing.JFrame frameSkillUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPower;
    private javax.swing.JLabel lblSkill;
    private javax.swing.JPanel pnlControl;
    private javax.swing.JPanel pnlSkill;
    private javax.swing.JSlider sliderSkillPower;
    private javax.swing.JTable tblSkills;
    private javax.swing.JTextField txtSkill;
    // End of variables declaration//GEN-END:variables
}
